services:
    portainer:
        image: portainer/portainer-ee:alpine
        hostname: portainer
        container_name: portainer
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "wget --no-verbose --tries=3 --spider http://portainer:9000 || exit 1"]
            interval: 1m
            timeout: 10s
            retries: 3
        networks:
            portainer:
                aliases:
                    - portainer
                    - portainer-ee
                ipv4_address: ${IPv4}
        ports:
            - "8000:8000"
            - "9000:9000"
            - "9443:9443"
        volumes:
            - portainer-data:/data
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

    portainer-tools:
        image: technorabilia/portainer-tools
        hostname: portainer-tools
        container_name: portainer-tools
        restart: unless-stopped
        networks:
            portainer:
                aliases:
                    - portainer-tools
                ipv4_address: ${IPv4_TOOLS}
        ports:
            - "9999:9999"
        volumes:
            - portainer-tools:/config
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

volumes:
    portainer-data:
        name: portainer-data
        driver: local
    portainer-tools:
        name: portainer-tools
        driver: local

networks:
    portainer:
        name: portainer
        driver: bridge
        ipam:
            config:
                - subnet: ${SUBNET}
